# Generated by Django 4.2.7 on 2023-11-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/')),
                ('price', models.FloatField()),
                ('ratings', models.IntegerField()),
            ],
        ),
    ]
