# Generated by Django 4.2.7 on 2023-11-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
