# Generated by Django 4.2.7 on 2023-11-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0003_contact_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
